# Generated by Django 2.1.11 on 2021-01-31 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume', '0053_language_addendum'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.IntegerField(default=2021),
        ),
    ]
