# Generated by Django 2.1.11 on 2021-01-31 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0054_auto_20210131_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='personal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resume.PersonalInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='personal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resume.PersonalInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='personal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resume.PersonalInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobaccomplishment',
            name='personal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resume.PersonalInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='personal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resume.PersonalInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='overview',
            name='personal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resume.PersonalInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programminglanguage',
            name='personal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resume.PersonalInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='personal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resume.PersonalInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='personal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resume.PersonalInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='personal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resume.PersonalInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skillset',
            name='personal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resume.PersonalInfo'),
            preserve_default=False,
        ),
    ]
