# Generated by Django 3.1 on 2021-02-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0056_auto_20210201_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='cv_pdf',
            field=models.FileField(blank=True, help_text='Downloadable resume file', null=True, upload_to='static/resume/img/'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/resume/img/'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='locality',
            field=models.CharField(blank=True, help_text='e.g. city such as Boston', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='region',
            field=models.CharField(blank=True, help_text='e.g. MA or Italy', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='site',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='suffix',
            field=models.CharField(blank=True, help_text='e.g. PhD', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='title',
            field=models.CharField(blank=True, help_text='e.g. Developer', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='twittername',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
