# Generated by Django 3.1 on 2021-03-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0058_remove_skillset_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skillurl',
            field=models.URLField(blank=True, verbose_name='Skill URL'),
        ),
    ]
