# Generated by Django 3.1 on 2021-03-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0059_skill_skillurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skillurl',
            field=models.URLField(blank=True, null=True, verbose_name='Skill URL'),
        ),
    ]
