# Generated by Django 3.1 on 2021-03-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0061_auto_20210311_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='personal',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='language',
            field=models.ManyToManyField(related_name='mes_language', to='resume.Language'),
        ),
    ]
