# Generated by Django 3.1 on 2021-03-17 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0062_auto_20210316_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='language',
            new_name='name',
        ),
    ]
