# Generated by Django 3.1 on 2021-03-17 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0064_auto_20210317_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='language',
        ),
    ]
