# Generated by Django 3.1 on 2021-03-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0065_remove_personalinfo_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='language',
            field=models.ManyToManyField(related_name='mes_language', through='resume.MesLanguages', to='resume.Language'),
        ),
    ]
