# Generated by Django 3.1 on 2021-03-17 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0066_personalinfo_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='language',
        ),
    ]
