# Generated by Django 3.1 on 2021-03-17 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0067_remove_personalinfo_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MesLanguages',
        ),
    ]
