# Generated by Django 3.1 on 2021-03-17 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0068_delete_meslanguages'),
    ]

    operations = [
        migrations.CreateModel(
            name='MesLanguages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.language')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.personalinfo')),
            ],
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='language',
            field=models.ManyToManyField(related_name='mes_language', through='resume.MesLanguages', to='resume.Language'),
        ),
    ]
