# Generated by Django 3.1 on 2021-03-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0069_auto_20210317_2118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name'], 'verbose_name_plural': '10. Languages'},
        ),
        migrations.AlterModelOptions(
            name='meslanguages',
            options={'ordering': ['order', 'id'], 'verbose_name_plural': 'Mes languages'},
        ),
        migrations.RemoveField(
            model_name='language',
            name='addendum',
        ),
        migrations.RemoveField(
            model_name='language',
            name='level',
        ),
        migrations.RemoveField(
            model_name='language',
            name='order',
        ),
        migrations.AddField(
            model_name='meslanguages',
            name='addendum',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='meslanguages',
            name='level',
            field=models.IntegerField(choices=[(5, 'Native'), (4, 'Full professional proficiency'), (3, 'Professional working proficiency'), (2, 'Limited professional proficiency'), (1, 'Elementary professional proficiency')], default=5, help_text='Choice between 1 and 5'),
        ),
        migrations.AddField(
            model_name='meslanguages',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
