# Generated by Django 3.1 on 2021-03-26 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0071_remove_programminglanguage_personal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programminglanguage',
            options={'ordering': ['name', 'id'], 'verbose_name_plural': '09. Programming languages'},
        ),
        migrations.RemoveField(
            model_name='programminglanguage',
            name='level',
        ),
        migrations.RemoveField(
            model_name='programminglanguage',
            name='order',
        ),
        migrations.CreateModel(
            name='MesLanguageProgrammation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(5, 'Expert'), (4, 'Advanced'), (3, 'Intermediate'), (2, 'Novice'), (1, 'Fundamental Awareness')], help_text='Choice between 1 and 5')),
                ('order', models.IntegerField(default=1)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.personalinfo')),
                ('programming_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.programminglanguage')),
            ],
            options={
                'verbose_name_plural': '09. Programming languages',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='programming_language',
            field=models.ManyToManyField(related_name='mes_programming_language', through='resume.MesLanguageProgrammation', to='resume.ProgrammingLanguage'),
        ),
    ]
