# Generated by Django 3.1 on 2022-02-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0073_auto_20210607_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.IntegerField(default=2022),
        ),
    ]
